# Generated by Django 5.0.6 on 2026-05-06 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0007_productcomment_productcommentimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Shaxsiy izoh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='products.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Saqlangan mahsulot',
                'verbose_name_plural': 'Saqlangan mahsulotlar',
                'db_table': 'marketplace_saved_product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_user_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_saved_product_per_user'),
        ),
    ]
