# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_inquiry", "Yangi so'rov"),
                            ("order_offer", "Taklif qabul qilindi"),
                            ("order_paid", "To'lov qilindi"),
                            ("order_shipped", "Jo'natildi"),
                            ("order_delivered", "Yetkazib berildi"),
                            ("order_completed", "Buyurtma yakunlandi"),
                            ("order_cancelled", "Buyurtma bekor qilindi"),
                            ("order_dispute", "Bahs ochilgan"),
                            ("new_message", "Yangi xabar"),
                            ("contact_unlocked", "Contact ochilgan"),
                            ("escrow_released", "Escrow sotuvchiga o'tdi"),
                            ("escrow_refunded", "Escrow xaridorga qaytdi"),
                            ("kyc_approved", "KYC tasdiqlandi"),
                            ("kyc_rejected", "KYC rad etildi"),
                            ("verification_reminder", "Tasdiqlash eslatmasi"),
                            ("blacklist_report", "Qora ro'yxat hisoboti"),
                            ("blacklist_verified", "Qora ro'yxat tasdiqlandi"),
                        ],
                        max_length=30,
                        verbose_name="Turi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sarlavha")),
                ("message", models.TextField(verbose_name="Xabar matni")),
                (
                    "action_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Action URL"),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Rasm URL")),
                ("is_read", models.BooleanField(default=False, verbose_name="O'qilganmi?")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti"),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Related ID"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qabul qiluvchi",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Related turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "Ilova ichidagi"),
                            ("email", "Email"),
                            ("push", "Push (mobile/web)"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                        verbose_name="Kanal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("sent", "Yuborildi"),
                            ("delivered", "Yetkazildi"),
                            ("failed", "Xatolik"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provider message ID"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Xatolik xabari")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Yuborilgan vaqti"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Yetkazilgan vaqti"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification delivery",
                "verbose_name_plural": "Notification deliveries",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True, verbose_name="Email faol?")),
                ("push_enabled", models.BooleanField(default=True, verbose_name="Push faol?")),
                (
                    "telegram_enabled",
                    models.BooleanField(default=False, verbose_name="Telegram faol?"),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Telegram chat ID"),
                ),
                (
                    "type_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"order_inquiry": {"email": true, "push": true}, ...}',
                        verbose_name="Turlar bo'yicha sozlamalar",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="Jim vaqt boshlanishi"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="Jim vaqt tugashi"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification sozlamasi",
                "verbose_name_plural": "Notification sozlamalari",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notificatio_recipie_684eac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"], name="notificatio_notific_d8746a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationdelivery",
            unique_together={("notification", "channel")},
        ),
    ]
