# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPrice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reveal_phone", "Telefonni ko'rish"),
                            ("reveal_email", "Emailni ko'rish"),
                            ("open_chat", "Chatni ochish"),
                            ("priority_lead", "Navbatdan tashqari lead"),
                            ("boost_listing", "E'lonni yuqoriga ko'tarish"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Action",
                    ),
                ),
                ("credits", models.PositiveIntegerField(default=1, verbose_name="Credit soni")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Credit narxi",
                "verbose_name_plural": "Credit narxlari",
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reveal_phone", "Telefonni ko'rish"),
                            ("reveal_email", "Emailni ko'rish"),
                            ("open_chat", "Chatni ochish"),
                            ("priority_lead", "Navbatdan tashqari lead"),
                            ("boost_listing", "E'lonni yuqoriga ko'tarish"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("credits_used", models.PositiveIntegerField(verbose_name="Ishlatilgan credit")),
                (
                    "converted_to_order",
                    models.BooleanField(default=False, verbose_name="Buyurtmaga aylanganmi?"),
                ),
                (
                    "viewed_by_seller_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sotuvchi ko'rgan vaqti"
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_credit_spends",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Maqsad foydalanuvchi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit tranzaksiyasi",
                "verbose_name_plural": "Credit tranzaksiyalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
