# Generated by Django 5.0.6 on 2026-05-02 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0001_initial"),
        ("services", "0002_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-rating", "-created_at"],
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="service",
            name="location",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="service",
            name="user",
        ),
        migrations.AddField(
            model_name="service",
            name="currently_at_location",
            field=models.CharField(blank=True, max_length=300, verbose_name="Hozirgi joylashuv"),
        ),
        migrations.AddField(
            model_name="service",
            name="currently_working",
            field=models.BooleanField(default=False, verbose_name="Hozirda ishlamoqda?"),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="service",
            name="is_open_for_booking",
            field=models.BooleanField(default=True, verbose_name="Yangi buyurtma qabul qilyapti?"),
        ),
        migrations.AddField(
            model_name="service",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed price"),
                    ("hourly", "Per hour"),
                    ("scope", "Scope-based"),
                    ("negotiable", "Negotiable"),
                ],
                default="fixed",
                max_length=20,
                verbose_name="Narx turi",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["seller", "internal_supplier"]},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mutaxassis",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(default="Xizmat", max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="service",
            name="working_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"mon": {"open": "09:00", "close": "18:00"}, ...}',
                verbose_name="Ish soatlari",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("design", "Dizayn"),
                    ("installation", "O'rnatish/Montaj"),
                    ("repair", "Ta'mirlash"),
                    ("upholstery", "Perig'iv/tikish"),
                    ("assembly", "Yig'ish"),
                    ("delivery", "Yetkazib berish"),
                    ("other", "Boshqa"),
                ],
                default="other",
                max_length=20,
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="projects_completed",
            field=models.PositiveIntegerField(default=0, verbose_name="Yakunlangan loyihalar"),
        ),
        migrations.AlterField(
            model_name="service",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=2, verbose_name="Reyting"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="review_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Sharhlar soni"),
        ),
        migrations.AlterField(
            model_name="service",
            name="starting_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Boshlang'ich narx"
            ),
        ),
        migrations.CreateModel(
            name="ProviderAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                ("time_start", models.TimeField(verbose_name="Boshlanish")),
                ("time_end", models.TimeField(verbose_name="Tugash")),
                ("is_booked", models.BooleanField(default=False, verbose_name="Bandmi?")),
                ("is_blocked", models.BooleanField(default=False, verbose_name="Bloklangan?")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mutaxassis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bandlik vaqti",
                "verbose_name_plural": "Bandlik vaqtlari",
                "ordering": ["date", "time_start"],
                "unique_together": {("provider", "date", "time_start")},
            },
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "So'rov"),
                            ("queue", "Navbatda"),
                            ("scheduled", "Rejalashtirilgan"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                            ("disputed", "Nizo"),
                        ],
                        default="inquiry",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Rejalashtirilgan sana"),
                ),
                (
                    "scheduled_time_start",
                    models.TimeField(blank=True, null=True, verbose_name="Boshlanish vaqti"),
                ),
                (
                    "scheduled_time_end",
                    models.TimeField(blank=True, null=True, verbose_name="Tugash vaqti"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Ish tavsifi"),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="Manzil")),
                (
                    "agreed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Kelishilgan narx",
                    ),
                ),
                (
                    "last_progress_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi progress yangilanishi"
                    ),
                ),
                (
                    "last_progress_text",
                    models.TextField(blank=True, verbose_name="Oxirgi progress matni"),
                ),
                (
                    "last_progress_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/progress/%Y/%m/",
                        verbose_name="Oxirgi progress rasmi",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Yakunlangan vaqti"),
                ),
                (
                    "customer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mijoz bahosi"
                    ),
                ),
                ("customer_review", models.TextField(blank=True, verbose_name="Mijoz sharhi")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "escrow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_booking",
                        to="escrow.escrow",
                        verbose_name="Escrow",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="services.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat buyurtmasi",
                "verbose_name_plural": "Xizmat buyurtmalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProgressUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(verbose_name="Yangilanish matni")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/progress/%Y/%m/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="Joylashuv"),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inquiry", "So'rov"),
                            ("queue", "Navbatda"),
                            ("scheduled", "Rejalashtirilgan"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                            ("disputed", "Nizo"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Yangi status (agar o'zgargan bo'lsa)",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="services.servicebooking",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mutaxassis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress yangilanishi",
                "verbose_name_plural": "Progress yangilanishlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
