# Generated by Django 5.0.6 on 2026-04-29 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Kontent identifikatori (masalan: nav_home)', max_length=255)),
                ('value', models.TextField(help_text="Ko'rinadigan matn yoki yozuv")),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=10)),
            ],
            options={
                'verbose_name': 'Sahifa kontenti',
                'verbose_name_plural': 'Sahifa kontentlari',
                'db_table': 'pages_content',
                'unique_together': {('key', 'language')},
            },
        ),
    ]
