# Generated by Django 5.2.6 on 2026-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_stir'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Hisob raqami', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Shartnoma raqami', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfo',
            field=models.CharField(blank=True, help_text='MFO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stir',
            field=models.CharField(blank=True, help_text='STIR (INN)', max_length=20, null=True),
        ),
    ]
