# Generated by Django 5.2.6 on 2026-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bank_account_profile_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='UI/UX preferences (colors, layout, etc.)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_intro',
            field=models.FileField(blank=True, null=True, upload_to='profiles/intros/'),
        ),
    ]
