# Generated by Django 5.2.6 on 2026-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_preferences_profile_video_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer (Xaridor)'), ('seller', 'Sotuvchi (Legacy)'), ('internal_supplier', "Ichki ta'minotchi (Legacy)"), ('admin', 'Admin'), ('super_admin', 'Super admin'), ('partner_material', 'Xom-ashyo hamkori'), ('partner_service', "Servis hamkori (Sug'urta/Kredit)"), ('designer_interior', 'Interyer dizayner'), ('designer_3d', '3D Dizayner'), ('fixer_master', "O'rnatuvchi usta (Sborka)"), ('fixer_repair', "Ta'mirlash ustasi"), ('seller_retail', 'Chakana sotuvchi (Retail)'), ('seller_manufacturer', 'Ishlab chiqaruvchi (Manufacturer)'), ('seller_logistics', 'Logistika (Dostavka)'), ('seller_component', 'Furnitura va qismlar sotuvchisi')], db_index=True, default='customer', max_length=24),
        ),
    ]
