# Generated by Django 5.2.6 on 2026-05-05 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('cover_image', models.ImageField(upload_to='showroom/portfolio/%Y/%m/', verbose_name='Asosiy rasm')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joylashuv')),
                ('completed_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bajarilgan yil')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('seller', models.ForeignKey(limit_choices_to={'role__in': ['seller', 'internal_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Portfolio elementi',
                'verbose_name_plural': 'Portfolio elementlari',
                'db_table': 'showroom_portfolio_item',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['seller', 'is_published'], name='showroom_po_seller__d89085_idx')],
            },
        ),
    ]
