# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0004_productfileaccessrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="Miqdori")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Mavjud"),
                            ("reserved", "Zaxiraga olingan"),
                            ("out_of_stock", "Tugagan"),
                            ("incoming", "Yo'lda/kutilmoqda"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "reserved_qty",
                    models.PositiveIntegerField(default=0, verbose_name="Zaxiraga olingan"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="products.product",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaxira",
                "verbose_name_plural": "Zaxiralar",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Miqdori")),
                ("is_released", models.BooleanField(default=False, verbose_name="Qaytarilganmi?")),
                (
                    "released_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Qaytarilgan vaqti"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="orders.order",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="warehouse.stock",
                        verbose_name="Zaxira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaxira olish",
                "verbose_name_plural": "Zaxira olishlar",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ombor nomi")),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("home", "O'z uy/ofis"),
                            ("external", "Ijaraga olingan ombor"),
                            ("supplier", "Yetkazib beruvchi (drop-ship)"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="Ombor turi",
                    ),
                ),
                ("address", models.TextField(help_text="To'liq manzil", verbose_name="Manzil")),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kenglik",
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Uzunlik",
                    ),
                ),
                (
                    "external_erp_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Tashqi ERP ID"),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi sinxronlash vaqti"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["seller", "internal_supplier"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sotuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombor",
                "verbose_name_plural": "Omborlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="warehouse.warehouse",
                verbose_name="Ombor",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["product", "status"], name="warehouse_s_product_1496ca_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "status"], name="warehouse_s_warehou_200975_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("warehouse", "product", "variant")},
        ),
    ]
