# Generated by Django 5.0.6 on 2026-05-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('location', models.CharField(default='Toshkent', max_length=255)),
                ('experience', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(default='Barchasi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xizmat/Usta',
                'verbose_name_plural': 'Xizmatlar va Ustalar',
            },
        ),
    ]
