# Generated by Django 5.0.6 on 2026-05-01 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa')),
                ('status', models.CharField(choices=[('held', "Mablag' ushlab turilibdi (Muzlatilgan)"), ('released', "Mablag' sotuvchiga o'tkazildi"), ('refunded', "Mablag' xaridorga qaytarildi"), ('disputed', 'Bahsli holat')], default='held', max_length=20, verbose_name='Holati')),
                ('dispute_reason', models.TextField(blank=True, null=True, verbose_name='Bahs sababi')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_escrows', to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='orders.order', verbose_name='Buyurtma')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_escrows', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Escrow bitimi',
                'verbose_name_plural': 'Escrow bitimlari',
            },
        ),
    ]
