# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontent",
            options={
                "verbose_name": "Sahifa kontenti (legacy)",
                "verbose_name_plural": "Sahifa kontentlari (legacy)",
            },
        ),
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="Slug / URL yo'lakchasi"
                    ),
                ),
                (
                    "full_path",
                    models.CharField(
                        help_text="Masalan: /services/installation",
                        max_length=500,
                        unique=True,
                        verbose_name="To'liq yo'l",
                    ),
                ),
                ("title_uz", models.CharField(max_length=200, verbose_name="Sarlavha (UZ)")),
                (
                    "title_ru",
                    models.CharField(blank=True, max_length=200, verbose_name="Sarlavha (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=200, verbose_name="Sarlavha (EN)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("scheduled", "Rejalashtirilgan"),
                            ("published", "Nashr qilingan"),
                            ("archived", "Arxivlangan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Ochiq (hamma ko'radi)"),
                            ("authenticated", "Faqat tizimga kirganlar"),
                            ("role_restricted", "Rol cheklamali"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Ko'rinish",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["seller", "admin"] - visibility=role_restricted uchun',
                        verbose_name="Ruxsat etilgan rollar",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Nashr vaqti"),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Standart"),
                            ("landing", "Landing page"),
                            ("docs", "Hujjatlar"),
                            ("form", "Forma"),
                        ],
                        default="default",
                        max_length=50,
                        verbose_name="Shablon",
                    ),
                ),
                (
                    "header_variant",
                    models.CharField(
                        default="default", max_length=50, verbose_name="Header varianti"
                    ),
                ),
                (
                    "footer_variant",
                    models.CharField(
                        default="default", max_length=50, verbose_name="Footer varianti"
                    ),
                ),
                ("custom_css", models.TextField(blank=True, verbose_name="Maxsus CSS")),
                ("custom_js", models.TextField(blank=True, verbose_name="Maxsus JS")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratuvchi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="pages.cmspage",
                        verbose_name="Ota sahifa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oxirgi tahrirlagan",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Sahifa",
                "verbose_name_plural": "CMS Sahifalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMSSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero block"),
                            ("banner", "Banner"),
                            ("text_plain", "Oddiy matn"),
                            ("text_rich", "Rich text (WYSIWYG)"),
                            ("product_slider", "Mahsulot slider"),
                            ("service_slider", "Xizmat slider"),
                            ("category_grid", "Kategoriya grid"),
                            ("faq", "FAQ accordion"),
                            ("gallery", "Rasm galereyasi"),
                            ("video", "Video embed"),
                            ("model_3d", "3D model (GLB)"),
                            ("html", "Custom HTML"),
                            ("cta", "Call-to-action"),
                            ("testimonials", "Fikrlar"),
                            ("form", "Lead capture form"),
                        ],
                        max_length=30,
                        verbose_name="Sektsiya turi",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Tartib")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Ochiq (hamma ko'radi)"),
                            ("authenticated", "Faqat tizimga kirganlar"),
                            ("role_restricted", "Rol cheklamali"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Ko'rinish",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ruxsat etilgan rollar"
                    ),
                ),
                ("content_uz", models.JSONField(default=dict, verbose_name="Kontent (UZ)")),
                (
                    "content_ru",
                    models.JSONField(blank=True, default=dict, verbose_name="Kontent (RU)"),
                ),
                (
                    "content_en",
                    models.JSONField(blank=True, default=dict, verbose_name="Kontent (EN)"),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, max_length=50, verbose_name="Fon rangi"),
                ),
                (
                    "text_color",
                    models.CharField(blank=True, max_length=50, verbose_name="Matn rangi"),
                ),
                (
                    "padding_top",
                    models.CharField(default="40px", max_length=20, verbose_name="Yuqori padding"),
                ),
                (
                    "padding_bottom",
                    models.CharField(default="40px", max_length=20, verbose_name="Pastgi padding"),
                ),
                (
                    "is_full_width",
                    models.BooleanField(default=False, verbose_name="To'liq kenglik?"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="pages.cmspage",
                        verbose_name="Sahifa",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Sektsiya",
                "verbose_name_plural": "CMS Sektsiyalar",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField(verbose_name="Revisiya raqami")),
                ("data", models.JSONField(verbose_name="Sahifa ma'lumotlari (snapshot)")),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("is_auto_save", models.BooleanField(default=False, verbose_name="Avto-saqlash?")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratuvchi",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="pages.cmspage",
                        verbose_name="Sahifa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sahifa revisiyasi",
                "verbose_name_plural": "Sahifa revisiyalari",
                "ordering": ["-revision_number"],
                "unique_together": {("page", "revision_number")},
            },
        ),
    ]
