# Generated by Django 5.0.6 on 2026-04-30 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('inquiry', "So'rov (Inquiry)"), ('offer', 'Taklif (Offer)'), ('negotiation', 'Muzokara (Negotiation)'), ('escrow_pending', "To'lov kutilmoqda (Escrow Pending)"), ('paid', "To'langan (Paid)"), ('started', 'Boshlangan (Started)'), ('production', 'Ishlab chiqarilmoqda (Production)'), ('shipping', 'Yetkazib berilmoqda (Shipping)'), ('delivered', 'Yetkazib berildi (Delivered)'), ('completed', 'Yakunlandi (Completed)'), ('canceled', 'Bekor qilindi (Canceled)'), ('disputed', 'Bahsli (Disputed)')], db_index=True, default='inquiry', max_length=24)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Umumiy narx')),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, help_text="Escrow'da ushlab turilgan summa", max_digits=14)),
                ('shipping_address', models.TextField(blank=True, verbose_name='Yetkazib berish manzili')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Aloqa telefoni')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_orders', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'db_table': 'orders_item',
            },
        ),
    ]
