# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Maqsad telefoni"),
                ),
                (
                    "target_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Maqsad email"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("fraud_buyer", "Firibgar xaridor"),
                            ("unpaid_buyer", "To'lamagan xaridor"),
                            ("scam_supplier", "Firibgar yetkazib beruvchi"),
                            ("abuse", "Haqorat/qo'pol muomala"),
                            ("harassment", "Taqib/Terror"),
                            ("fake_product", "Soxta mahsulot"),
                        ],
                        max_length=20,
                        verbose_name="Tur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("verified", "Tasdiqlangan"),
                            ("disputed", "Bahslanmoqda"),
                            ("cleared", "Tozalangan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Sabab")),
                (
                    "evidence_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Screenshot, chat export, invoice, etc.",
                        verbose_name="Dalil fayllar",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqti"
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Admin izohi")),
                ("upvotes", models.PositiveIntegerField(default=0, verbose_name="Ovozlar (ha)")),
                (
                    "downvotes",
                    models.PositiveIntegerField(default=0, verbose_name="Ovozlar (yo'q)"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hisobotchi",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "super_admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ko'rib chiqqan",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Maqsad foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qora ro'yxat yozuvi",
                "verbose_name_plural": "Qora ro'yxat yozuvlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlacklistVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_upvote", models.BooleanField(verbose_name="Ha ovozi?")),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="blacklist.blacklistentry",
                        verbose_name="Yozuv",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ovoz bergan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qora ro'yxat ovozi",
                "verbose_name_plural": "Qora ro'yxat ovozlari",
            },
        ),
        migrations.AddIndex(
            model_name="blacklistentry",
            index=models.Index(
                fields=["target_user", "status"], name="blacklist_b_target__4c1735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistentry",
            index=models.Index(
                fields=["entry_type", "status"], name="blacklist_b_entry_t_8d0673_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blacklistvote",
            unique_together={("entry", "voter")},
        ),
    ]
