# Generated by Django 5.0.6 on 2026-04-27 09:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthMethodConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email_password", "Email + password"),
                            ("email_otp", "Email OTP"),
                            ("phone_otp", "Phone OTP"),
                            ("google", "Google"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Provider-specific config."
                    ),
                ),
            ],
            options={
                "db_table": "auth_methods_config",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email_password", "Email + password"),
                            ("email_otp", "Email OTP"),
                            ("phone_otp", "Phone OTP"),
                            ("google", "Google"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=24,
                    ),
                ),
                ("refresh_jti", models.CharField(max_length=64, unique=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("geo_country", models.CharField(blank=True, max_length=2)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "auth_methods_session",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialIdentity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("email_password", "Email + password"),
                            ("email_otp", "Email OTP"),
                            ("phone_otp", "Phone OTP"),
                            ("google", "Google"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=24,
                    ),
                ),
                ("subject", models.CharField(db_index=True, max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "auth_methods_social_identity",
            },
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target", models.CharField(db_index=True, max_length=160)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("login", "Login"),
                            ("reset", "Reset password"),
                            ("verify", "Verify channel"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email_password", "Email + password"),
                            ("email_otp", "Email OTP"),
                            ("phone_otp", "Phone OTP"),
                            ("google", "Google"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=24,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "auth_methods_otp",
                "indexes": [
                    models.Index(fields=["target", "purpose"], name="auth_method_target_cefe3c_idx")
                ],
            },
        ),
    ]
