# Generated by Django 5.0.6 on 2026-04-30 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Username 3-30 ta belgidan iborat bo'lishi kerak. Harflar, raqamlar, bo'shliq, chiziqcha va pastki chiziqcha ruxsat etiladi.", regex='^[a-zA-Z0-9][a-zA-Z0-9\\s_-]{2,29}$')]),
        ),
    ]
