# Generated by Django 5.0.6 on 2026-05-01 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Balans')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Muzlatilgan balans')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hamyon',
                'verbose_name_plural': 'Hamyonlar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deposit', "To'ldirish"), ('withdraw', 'Yechish'), ('transfer', "O'tkazma"), ('freeze', 'Muzlatish'), ('unfreeze', 'Muzlatishdan chiqarish'), ('payment', "To'lov")], max_length=20, verbose_name='Turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tashqi ID')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name="Meta ma'lumotlar")),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.wallet', verbose_name='Hamyon')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
