# Generated by Django 5.0.6 on 2026-04-27 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=120)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "security_audit_log",
            },
        ),
        migrations.CreateModel(
            name="IpBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("reason", models.CharField(max_length=200)),
                ("until", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "security_ip_block",
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=400)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "security_request_log",
            },
        ),
    ]
