# Generated by Django 5.0.6 on 2026-04-29 11:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbek)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Rus)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nomi (English)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0)),
                ('rght', models.PositiveIntegerField(db_index=True, default=0)),
                ('tree_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/covers/')),
                ('product_type_filter', models.CharField(choices=[('standard', 'Tayyor mahsulot'), ('manufacturing', 'Buyurtma asosida ishlab chiqarish')], default='standard', max_length=20, verbose_name='Mahsulot turi')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='categories/og/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'products_category',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_type', models.CharField(choices=[('standard', 'Tayyor mahsulot'), ('manufacturing', 'Buyurtma asosida ishlab chiqarish')], db_index=True, default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tekshirilmoqda'), ('published', 'Faol'), ('rejected', 'Rad etildi'), ('archived', 'Arxiv')], db_index=True, default='draft', max_length=20)),
                ('subcategory_path', models.CharField(blank=True, help_text="Kategoriya daraxt yo'li (denormalized)", max_length=500)),
                ('title_uz', models.CharField(max_length=200, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (Rus)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (English)')),
                ('description_uz', models.TextField(verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Rus)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (English)')),
                ('materials', models.JSONField(blank=True, default=list, help_text="Materiallar ro'yxati (Material.choices)")),
                ('primary_material', models.CharField(blank=True, choices=[('solid_wood', "Tabiiy yog'och (massiv)"), ('mdf', 'MDF'), ('chipboard', 'LDSP (yirik hissali)'), ('plywood', 'Fanera'), ('metal', 'Metall'), ('glass', 'Shisha'), ('plastic', 'Plastik'), ('rattan', 'Rattan'), ('leather', 'Charm (haqiqiy)'), ('eco_leather', 'Eko-charm'), ('fabric', 'Mato'), ('velvet', 'Barxat'), ('marble', 'Mramor'), ('granite', 'Granit'), ('stone', 'Tosh'), ('other', 'Boshqa')], max_length=20, verbose_name='Asosiy material')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Eni (sm)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Balandligi (sm)')),
                ('depth_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Chuqurligi (sm)')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Uzunligi (sm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Og'irligi (kg)")),
                ('colors', models.JSONField(blank=True, default=list, help_text="Ranglar ro'yxati (Color.choices)")),
                ('primary_color', models.CharField(blank=True, choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('beige', 'Bej'), ('brown', 'Jigarrang'), ('walnut', "Yong'oq rang"), ('oak', 'Eshak terisi rang'), ('cherry', 'Gilos rang'), ('mahogany', 'Kizil-yashil'), ('red', 'Qizil'), ('blue', "Ko'k"), ('green', 'Yashil'), ('yellow', 'Sariq'), ('orange', "To'q sariq"), ('pink', 'Pushti'), ('purple', 'Siyohrang'), ('gold', 'Oltin'), ('silver', 'Kumush'), ('multi', "Ko'p rangli"), ('transparent', 'Shaffof'), ('other', 'Boshqa')], max_length=20, verbose_name='Asosiy rang')),
                ('style', models.CharField(blank=True, choices=[('modern', 'Zamonaviy'), ('classic', 'Klassik'), ('scandinavian', 'Skandinav'), ('loft', 'Loft'), ('minimalism', 'Minimalizm'), ('high_tech', 'High-tech'), ('provence', 'Provans'), ('eco', 'Eco'), ('vintage', 'Vintage'), ('oriental', 'Sharq uslubi'), ('other', 'Boshqa')], max_length=20, verbose_name='Uslub')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('used', 'Foydalanilgan'), ('refurbished', 'Restavratsiya qilingan'), ('antique', 'Antikvar')], default='new', max_length=20, verbose_name='Holati')),
                ('is_outdoor', models.BooleanField(default=False, verbose_name='Tashqi mebel')),
                ('is_assembly_required', models.BooleanField(default=True, verbose_name="Yig'ilishi kerak")),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Joriy narx')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Eski narx')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_start', models.DateTimeField(blank=True, null=True)),
                ('discount_end', models.DateTimeField(blank=True, null=True)),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='Zaxira')),
                ('is_in_stock', models.BooleanField(db_index=True, default=True)),
                ('moq', models.PositiveIntegerField(default=1, help_text='Eng kam buyurtma soni', verbose_name='Minimal buyurtma (MOQ)')),
                ('max_qty', models.PositiveIntegerField(blank=True, help_text="Bir martada ko'p buyurtma mumkin (null = cheksiz)", null=True, verbose_name='Maksimal buyurtma')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Minimal narx')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Maksimal narx')),
                ('production_time_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ishlab chiqarish vaqti (kun)')),
                ('hashtags', models.CharField(blank=True, help_text='Virgul bilan ajratilgan hashtaglar', max_length=500)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(limit_choices_to={'role__in': ['seller', 'internal_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('downloadable', 'Yuklab olinadigan'), ('production', 'Ishlab chiqarish fayllari'), ('blueprint', 'Chizmalar/Blueprint')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Ochiq'), ('on_request', "So'rov orqali"), ('paid', "To'lovli")], max_length=20)),
                ('file', models.FileField(upload_to='products/files/%Y/%m/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unlock_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product')),
            ],
            options={
                'db_table': 'products_product_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/')),
                ('alt_uz', models.CharField(blank=True, max_length=200)),
                ('alt_ru', models.CharField(blank=True, max_length=200)),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'products_product_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=100, verbose_name='Variant nomi')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('depth_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text="Qo'shimcha narx (+/-)", max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'products_product_variant',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_in_stock'], name='products_pr_status_069beb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='products_pr_seller__2449b8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status'], name='products_pr_product_03ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'created_at'], name='products_pr_is_feat_5efbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['style', 'status'], name='products_pr_style_16f9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['condition', 'status'], name='products_pr_conditi_82163f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_primary_image_per_product'),
        ),
    ]
