# Generated by Django 5.0.6 on 2026-05-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_glb_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (Rus)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (Rus)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi (Rus)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz_en',
            field=models.CharField(max_length=100, null=True, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz_en',
            field=models.TextField(null=True, verbose_name="Tavsif (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz_ru',
            field=models.TextField(null=True, verbose_name="Tavsif (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz_uz',
            field=models.TextField(null=True, verbose_name="Tavsif (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (Rus)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz_en',
            field=models.CharField(max_length=200, null=True, verbose_name="Sarlavha (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz_ru',
            field=models.CharField(max_length=200, null=True, verbose_name="Sarlavha (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="Sarlavha (O'zbek)"),
        ),
    ]
