# Generated by Django 5.0.6 on 2026-04-27 09:42

import apps.users.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must be 3-30 chars, lowercase letters/digits/_/-, and start with a letter or digit.",
                                regex="^[a-z0-9][a-z0-9_-]{2,29}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("seller", "Seller"),
                            ("internal_supplier", "Internal supplier"),
                            ("admin", "Admin"),
                            ("super_admin", "Super admin"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=24,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        default="individual",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("kyc_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="KycDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("passport", "Passport / ID"),
                            ("registration", "Company registration"),
                            ("tax", "Tax certificate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="kyc/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_kyc_document",
            },
        ),
        migrations.CreateModel(
            name="PermissionGrant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action_key", models.CharField(db_index=True, max_length=120)),
                ("allowed", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_permission_grant",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/covers/"),
                ),
                (
                    "professions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subset of Profession.choices for sellers.",
                    ),
                ),
                (
                    "phones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of {"number": "+998...", "visibility": "public|paid|private"}',
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_email_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("paid", "Reveal on paid unlock"),
                            ("private", "Private"),
                        ],
                        default="paid",
                        max_length=12,
                    ),
                ),
                ("telegram", models.CharField(blank=True, max_length=64)),
                ("website", models.URLField(blank=True)),
                ("address_text", models.CharField(blank=True, max_length=300)),
                (
                    "geo_lat",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "geo_lng",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private (only chat partners)"),
                            ("hidden", "Hidden"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("profile_views", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_profile",
            },
        ),
        migrations.CreateModel(
            name="ProfileAvatar",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.ImageField(upload_to="profiles/avatars/")),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatars",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": "users_profile_avatar",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="permissiongrant",
            unique_together={("user", "action_key")},
        ),
        migrations.AddConstraint(
            model_name="profileavatar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="uniq_primary_avatar_per_profile",
            ),
        ),
    ]
