# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_productfileaccessrequest"),
        ("users", "0004_profile_stir"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Ko'rish"),
                            ("cart", "Savatchaga qo'shish"),
                            ("contact", "Contact ochish"),
                            ("inquiry", "So'rov yuborish"),
                            ("offer", "Taklif"),
                            ("order", "Buyurtma"),
                        ],
                        max_length=20,
                        verbose_name="Event turi",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Qiymat",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_events",
                        to="products.product",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["seller", "internal_supplier"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_conversion_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sotuvchi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion hodisasi",
                "verbose_name_plural": "Conversion hodisalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP manzil"),
                ),
                (
                    "contact_unlocked",
                    models.BooleanField(default=False, verbose_name="Contact ochilganmi?"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="users.profile",
                        verbose_name="Profil",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewed_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ko'ruvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil ko'rishi",
                "verbose_name_plural": "Profil ko'rishlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "product_views",
                    models.PositiveIntegerField(default=0, verbose_name="Mahsulot ko'rishlari"),
                ),
                (
                    "product_views_unique",
                    models.PositiveIntegerField(default=0, verbose_name="Unikal ko'rishlar"),
                ),
                (
                    "add_to_cart_count",
                    models.PositiveIntegerField(default=0, verbose_name="Savatchaga qo'shilgan"),
                ),
                (
                    "wishlist_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sevimlilarga qo'shilgan"),
                ),
                (
                    "contact_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Contact bosishlar"),
                ),
                ("inquiries", models.PositiveIntegerField(default=0, verbose_name="So'rovlar")),
                ("orders", models.PositiveIntegerField(default=0, verbose_name="Buyurtmalar")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Daromad"
                    ),
                ),
                ("organic_views", models.PositiveIntegerField(default=0)),
                ("search_views", models.PositiveIntegerField(default=0)),
                ("ads_views", models.PositiveIntegerField(default=0)),
                ("referral_views", models.PositiveIntegerField(default=0)),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["seller", "internal_supplier"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sotuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kunlik statistika",
                "verbose_name_plural": "Kunlik statistikalar",
                "ordering": ["-date"],
                "unique_together": {("seller", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP manzil"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="organic, search, ads, referral, direct",
                        max_length=50,
                        verbose_name="Manba",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="products.product",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewed_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ko'ruvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot ko'rishi",
                "verbose_name_plural": "Mahsulot ko'rishlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"], name="analytics_p_product_87066f_idx"
                    ),
                    models.Index(
                        fields=["viewer", "-created_at"], name="analytics_p_viewer__a0b8a2_idx"
                    ),
                ],
            },
        ),
    ]
