# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapURL",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL")),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1, default=0.5, max_digits=2, verbose_name="Priority"
                    ),
                ),
                ("lastmod", models.DateTimeField(auto_now=True, verbose_name="Lastmod")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Sitemap URL",
                "verbose_name_plural": "Sitemap URLlar",
                "ordering": ["-priority", "url"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("old_path", models.CharField(max_length=500, verbose_name="Eski yo'l")),
                ("new_path", models.CharField(max_length=500, verbose_name="Yangi yo'l")),
                (
                    "is_permanent",
                    models.BooleanField(default=True, verbose_name="Doimiy redirect? (301)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=0, verbose_name="Murojaatlar soni"),
                ),
            ],
            options={
                "verbose_name": "Redirect",
                "verbose_name_plural": "Redirectlar",
                "indexes": [
                    models.Index(
                        fields=["old_path", "is_active"], name="seo_redirec_old_pat_fcf221_idx"
                    )
                ],
                "unique_together": {("old_path",)},
            },
        ),
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.CharField(max_length=50, verbose_name="Object ID")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Meta title"),
                ),
                ("meta_description", models.TextField(blank=True, verbose_name="Meta description")),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=500, verbose_name="Meta keywords"),
                ),
                ("og_title", models.CharField(blank=True, max_length=200, verbose_name="OG title")),
                ("og_description", models.TextField(blank=True, verbose_name="OG description")),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/og_images/%Y/%m/",
                        verbose_name="OG image",
                    ),
                ),
                (
                    "og_type",
                    models.CharField(default="website", max_length=50, verbose_name="OG type"),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Twitter card type",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Twitter title"),
                ),
                (
                    "twitter_description",
                    models.TextField(blank=True, verbose_name="Twitter description"),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/twitter_images/%Y/%m/",
                        verbose_name="Twitter image",
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, verbose_name="Canonical URL")),
                ("noindex", models.BooleanField(default=False, verbose_name="Noindex?")),
                ("nofollow", models.BooleanField(default=False, verbose_name="Nofollow?")),
                (
                    "schema_type",
                    models.CharField(
                        blank=True,
                        help_text="Product, Service, Organization, BreadcrumbList, etc.",
                        max_length=50,
                        verbose_name="Schema.org type",
                    ),
                ),
                (
                    "schema_data",
                    models.JSONField(blank=True, default=dict, verbose_name="JSON-LD data"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO metadata",
                "verbose_name_plural": "SEO metadatalar",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="seo_seometa_content_a438cb_idx"
                    )
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
