# Generated by Django 5.0.6 on 2026-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glb_model',
            field=models.FileField(blank=True, help_text="Mahsulotning 3D ko'rinishi uchun .glb fayli", null=True, upload_to='products/3d_models/%Y/%m/', verbose_name='3D Model (GLB)'),
        ),
    ]
