# Generated by Django 5.0.6 on 2026-05-02 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_name_en_en_category_name_en_ru_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFileAccessRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Nima uchun bu fayl kerakligi",
                        verbose_name="So'rov matni",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("denied", "Rad etildi"),
                            ("paid_pending", "To'lov kutilmoqda"),
                            ("paid_approved", "To'lov qilindi, tasdiqlandi"),
                            ("expired", "Muddati tugagan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "owner_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Tasdiqlash"),
                            ("deny", "Rad etish"),
                            ("request_payment", "To'lov so'rash"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Egasi qarori",
                    ),
                ),
                ("owner_note", models.TextField(blank=True, verbose_name="Egasi izohi")),
                (
                    "requested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="So'ralgan narx",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="To'langan summa",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="To'lov vaqti"),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ruxsat berilgan vaqti"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Muddati tugash vaqti"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="Yuklab olishlar soni"),
                ),
                (
                    "requester_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="So'rovchi IP"
                    ),
                ),
                (
                    "requester_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="So'rovchi joylashuvi"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="products.productfile",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_access_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="So'rovchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fayl ruxsat so'rovi",
                "verbose_name_plural": "Fayl ruxsat so'rovlari",
                "ordering": ["-created_at"],
                "unique_together": {("file", "requester")},
            },
        ),
    ]
