# Generated by Django 5.0.6 on 2026-05-06 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_name_en_af_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '—'), (1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=0, verbose_name='Reyting')),
                ('body', models.TextField(verbose_name='Sharh matni')),
                ('status', models.CharField(choices=[('approved', 'Tasdiqlangan'), ('pending', 'Tekshirilmoqda'), ('rejected', 'Rad etilgan')], db_index=True, default='approved', max_length=20, verbose_name='Holat')),
                ('is_verified_buyer', models.BooleanField(default=False, help_text='Bu foydalanuvchi mahsulotni haqiqatan sotib olganmi?', verbose_name='Tasdiqlangan xaridor')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Foydali deb belgilangan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.productcomment', verbose_name='Ota-sharh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot sharhi',
                'verbose_name_plural': 'Mahsulot sharhlari',
                'db_table': 'products_product_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCommentImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/comments/%Y/%m/', verbose_name='Rasm')),
                ('alt_uz', models.CharField(blank=True, max_length=200, verbose_name='Alt matn (uz)')),
                ('alt_ru', models.CharField(blank=True, max_length=200, verbose_name='Alt matn (ru)')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt matn (en)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productcomment', verbose_name='Sharh')),
            ],
            options={
                'verbose_name': 'Sharh rasmi',
                'verbose_name_plural': 'Sharh rasmlari',
                'db_table': 'products_product_comment_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['product', '-created_at'], name='comment_product_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['status', '-created_at'], name='comment_status_recent_idx'),
        ),
    ]
