# Generated by Django 5.2.6 on 2026-05-06 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_name_en_af_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Yangi'), ('used', 'Foydalanilgan'), ('refurbished', 'Restavratsiya qilingan'), ('antique', 'Antikvar')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='glb_model',
            field=models.FileField(blank=True, null=True, upload_to='products/3d_models/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_assembly_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Tanlangan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('beige', 'Bej'), ('brown', 'Jigarrang'), ('walnut', "Yong'oq rang"), ('oak', 'Eshak terisi rang'), ('cherry', 'Gilos rang'), ('mahogany', 'Kizil-yashil'), ('red', 'Qizil'), ('blue', "Ko'k"), ('green', 'Yashil'), ('yellow', 'Sariq'), ('orange', "To'q sariq"), ('pink', 'Pushti'), ('purple', 'Siyohrang'), ('gold', 'Oltin'), ('silver', 'Kumush'), ('multi', "Ko'p rangli"), ('transparent', 'Shaffof'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_material',
            field=models.CharField(blank=True, choices=[('solid_wood', "Tabiiy yog'och (massiv)"), ('mdf', 'MDF'), ('chipboard', 'LDSP (yirik hissali)'), ('plywood', 'Fanera'), ('metal', 'Metall'), ('glass', 'Shisha'), ('plastic', 'Plastik'), ('rattan', 'Rattan'), ('leather', 'Charm (haqiqiy)'), ('eco_leather', 'Eko-charm'), ('fabric', 'Mato'), ('velvet', 'Barxat'), ('marble', 'Mramor'), ('granite', 'Granit'), ('stone', 'Tosh'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_time_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role__in': ['seller', 'internal_supplier', 'seller_retail', 'seller_manufacturer', 'seller_logistics', 'seller_component', 'partner_material', 'partner_service', 'designer_interior', 'designer_3d', 'fixer_master', 'fixer_repair']}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('modern', 'Zamonaviy'), ('classic', 'Klassik'), ('scandinavian', 'Skandinav'), ('loft', 'Loft'), ('minimalism', 'Minimalizm'), ('high_tech', 'High-tech'), ('provence', 'Provans'), ('eco', 'Eco'), ('vintage', 'Vintage'), ('oriental', 'Sharq uslubi'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ProductFileAccessRequest',
        ),
    ]
